EXPERIMENT:
  NAME: ""
  TAG: "reviewkd,ResNet50,MobileNet_FAM_REVIEW_KD_PREACT"
  PROJECT: "imagenet_baselines"

DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 256

DISTILLER:
  TYPE: "FAM_REVIEW_KD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
FOURIER_REVIEW_CROSSATT:
  FAMKD_WEIGHT: 8.0
  SHAPES : [1, 7,14,28,56]
  OUT_SHAPES : [1, 7,14,28,56]
  IN_SHAPES : [1, 7,14, 28, 56]
  IN_CHANNELS_X: [128,256,512,1024, 1024]
  IN_CHANNELS : [256,512,1024, 1024, 1] # channel from residual
  MID_CHANNELS:  [128, 256,512,1024, 1024] 
  OUT_CHANNELS : [256,512,1024,2048, 2048]

  MAX_MID_CHANNEL : 512
  GUIDE_LAYERS : [1, 2, 3, 4, 5]
  STU_PREACT : True

  WARMUP_EPOCHS : 1

SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
  WANDB : False






