EXPERIMENT:
  NAME: ""
  TAG: "fam_kd,res324,res84"
  PROJECT: "cifar100_FAM_KD"
DISTILLER:
  TYPE: "FAM_KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
FAM_KD:
  REVIEWKD_WEIGHT: 20.0
  SHAPES : [1, 8,16,32]
  IN_SHAPES : [8,16, 32,1]
  OUT_SHAPES : [1, 8,16,32]
  IN_CHANNELS : [128,256,256,1]
  IN_CHANNELS_X : [64,128,256, 256]

  MID_CHANNELS: [64,128,256, 256]
  OUT_CHANNELS: [64,128,256, 256]
  MAX_MID_CHANNEL : 512
  GUIDE_LAYERS : [1, 2, 3,4]
  STU_PREACT : True

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "base"
LOG:
  WANDB: False




