EXPERIMENT:
  NAME: ""
  TAG: "fam_kd,res56,res20"
  PROJECT: "cifar100_FAM_KD"
DISTILLER:
  TYPE: "FAM_KD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
FAM_KD:
  CE_WEIGHT: 1.0
  FAMKD_WEIGHT: 0.8
  SHAPES : [1,8,16,32]

  OUT_SHAPES : [1,8,16,32]
  IN_SHAPES : [1,1,8,16]

  IN_CHANNELS_X : [16,32,64,64]
  IN_CHANNELS : [32,64,64,1]
  MID_CHANNELS: [16,32,64,64]
  OUT_CHANNELS : [16,32,64,64]
  MAX_MID_CHANNEL : 512

  GUIDE_LAYERS : [1, 2, 3, 4]
  STU_PREACT : False

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "base"
LOG:
  WANDB: True





