EXPERIMENT:
  NAME: ""
  TAG: "fam_kd,wrn402,wrn162"
  PROJECT: "cifar100_FAM_KD"
DISTILLER:
  TYPE: "FAM_KD_BUTTER"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_16_2"
FAM_KD:
  FAMKD_WEIGHT: 5.0
  CE_WEIGHT: 1.0
  SHAPES : [1,8,16,32]
  OUT_SHAPES : [1,8,16,32]
  IN_SHAPES : [1,1,8,16]
  IN_CHANNELS_X : [32,64,128,128]

  IN_CHANNELS : [64,128,128, 1]
  MID_CHANNELS: [32,64,128,128]
  OUT_CHANNELS : [32,64,128,128]

  MAX_MID_CHANNEL : 512
  GUIDE_LAYERS : [1, 2, 3, 4]
  STU_PREACT : False

SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "base"
LOG:
  WANDB: True





